name: Monthly Build

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 12 * *

jobs:
  build:
    name: Pull and Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: git tag
        uses: actions/github-script@v7
        id: tag
        with:
          script: |
            const now = new Date()
            return `${now.getFullYear()}${(now.getMonth() + 1).toString().padStart(2, '0')}${now.getDate().toString().padStart(2, '0')}`
          result-encoding: string

      - name: Push Tag
        run: |
          git config --global user.name 'Dreamacro'
          git config --global user.email 'dreamacro@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git tag ${{steps.tag.outputs.result}}
          git push origin ${{steps.tag.outputs.result}}
      
      - name: Download file
        env: 
          LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
        run: |
          wget -O ./GeoLite2-Country.tar.gz "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=${LICENSE_KEY}&suffix=tar.gz"
          tar zxvf ./GeoLite2-Country.tar.gz -C .
          mkdir dist
          mv ./GeoLite2-Country_*/GeoLite2-Country.mmdb ./dist/Country.mmdb

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/Country.mmdb
          tag_name: ${{steps.tag.outputs.result}}
      
      - name: Upload to release branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: release
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
